// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "input": string;
      "preset": string;
      "apiKey.openai": string;
      "apiKey.deepseek": string;
    };
  }
}
