// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "input": string;
      "aiChat.provider": string;
      "aiChat.endpoint": string;
      "aiChat.model": string;
      "aiChat.apiKey": string;
    };
  }
}
